// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dealer "github.com/textileio/broker-core/dealer"
)

// Dealer is an autogenerated mock type for the Dealer type
type Dealer struct {
	mock.Mock
}

// ReadyToCreateDeals provides a mock function with given fields: ctx, sdb
func (_m *Dealer) ReadyToCreateDeals(ctx context.Context, sdb dealer.AuctionDeals) error {
	ret := _m.Called(ctx, sdb)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dealer.AuctionDeals) error); ok {
		r0 = rf(ctx, sdb)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
