// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	types "github.com/textileio/broker-core/cmd/neard/nearclient/internal/types"
)

// DataChangesOption is an autogenerated mock type for the DataChangesOption type
type DataChangesOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *DataChangesOption) Execute(_a0 *types.ChangesRequest) {
	_m.Called(_a0)
}
