// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	cid "github.com/ipfs/go-cid"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// Uploader is an autogenerated mock type for the Uploader type
type Uploader struct {
	mock.Mock
}

// Store provides a mock function with given fields: ctx, r
func (_m *Uploader) Store(ctx context.Context, r io.Reader) (cid.Cid, error) {
	ret := _m.Called(ctx, r)

	var r0 cid.Cid
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader) cid.Cid); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Get(0).(cid.Cid)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, io.Reader) error); ok {
		r1 = rf(ctx, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
