apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: auctioneer-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: auctioneer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auctioneer-01
  labels:
    app: auctioneer
spec:
  serviceName: auctioneer
  replicas: 2
  selector:
    matchLabels:
      app: auctioneer-v1
  template:
    metadata:
      labels:
        app: auctioneer-v1
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 2000
        fsGroup: 2000
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: configure-auctioneer
          image: ubuntu:latest
          imagePullPolicy: IfNotPresent
          command:
            - bash
            - "-c"
            - |
              set -ex
              [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
              ordinal=${BASH_REMATCH[1]}
              cp /env/configAuctioneer$ordinal.env /data/auctioneerd/.env
          volumeMounts:
            - name: auctioneer-store
              mountPath: /data/auctioneerd
            - name: configure-env
              mountPath: /env
      containers:
        - name: auctioneer
          image: textile/auctioneer
          imagePullPolicy: Always
          env:
            - name: AUCTIONEER_GPUBSUB_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: gpubsub-project-id
            - name: AUCTIONEER_GPUBSUB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: gpubsub-api-key
          ports:
            - name: metrics
              containerPort: 9090
          volumeMounts:
            - name: auctioneer-store
              mountPath: /data/auctioneerd
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
      volumes:
        - name: configure-env
          configMap:
            name: configmap-auctioneer
  volumeClaimTemplates:
    - metadata:
        name: auctioneer-store
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi
