apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    app: auth
spec:
  selector:
    app: auth-v1
  ports:
    - port: 5000
      name: api
    - port: 9090
      name: metrics
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth
  labels:
    app: auth
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      app: auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-01
  labels:
    app: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-v1
  template:
    metadata:
      labels:
        app: auth-v1
    spec:
      serviceAccountName: postgres-cloud-sql
      containers:
        - name: auth
          image: textile/auth
          imagePullPolicy: Always
          ports:
            - name: api
              containerPort: 5000
            - name: metrics
              containerPort: 9090
          command: ["./with-postgres.sh", "./authd"]
          env:
            - name: DAEMON
              value: "auth"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: postgres-password
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: auth-db-password
          envFrom:
            - configMapRef:
                name: configmap-auth
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
          readinessProbe:
            tcpSocket:
              port: api
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: api
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
