apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: broker-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: broker
---
apiVersion: v1
kind: Service
metadata:
  name: broker
  labels:
     app: broker
spec:
  selector:
    app: broker-v1
  ports:
    - port: 5000
      name: api
    - port: 9090
      name: metrics
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: broker
  labels:
    app: broker
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      app: broker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-01
  labels:
    app: broker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: broker-v1
  template:
    metadata:
      labels:
        app: broker-v1
    spec:
      serviceAccountName: postgres-cloud-sql
      containers:
        - name: broker
          image: textile/broker
          imagePullPolicy: Always
          ports:
            - name: api
              containerPort: 5000
            - name: metrics
              containerPort: 9090
          command: ["./with-postgres.sh", "./brokerd"]
          env:
            - name: DAEMON
              value: "broker"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: postgres-password
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: broker-db-password
            - name: BROKER_GPUBSUB_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: gpubsub-project-id
            - name: BROKER_GPUBSUB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: gpubsub-api-key
          envFrom:
            - configMapRef:
                name: configmap-broker
          resources:
            requests:
              cpu: 250m
              memory: 512Mi              
          readinessProbe:
            tcpSocket:
              port: api
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: api
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
