apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: dealer-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: dealer
---
apiVersion: v1
kind: Service
metadata:
  name: dealer
  labels:
     app: dealer
spec:
  selector:
    app: dealer-v1 # point this to desired deployment
  ports:
    - port: 9090
      name: metrics
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dealer
  labels:
    app: dealer
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      app: dealer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealer-01
  labels:
    app: dealer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dealer-v1
  template:
    metadata:
      labels:
        app: dealer-v1
    spec:
      serviceAccountName: postgres-cloud-sql
      containers:
        - name: dealer
          image: textile/dealer
          imagePullPolicy: Always
          ports:
            - name: metrics
              containerPort: 9090
          command: ["./with-postgres.sh", "./dealerd"]
          env:
            - name: DAEMON
              value: "dealer"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: postgres-password
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: dealer-db-password
            - name: DEALER_GPUBSUB_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: gpubsub-project-id
            - name: DEALER_GPUBSUB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: gpubsub-api-key
          envFrom:
            - configMapRef:
                name: configmap-dealer
          resources:
            requests:
              cpu: 250m
              memory: 250Mi

