apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: near-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: near
---
apiVersion: v1
kind: Service
metadata:
  name: near
  labels:
     app: near
spec:
  selector:
    app: near-v1
  ports:
    - port: 5000
      name: api
    - port: 9090
      name: metrics
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: near
  labels:
    app: near
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      app: near
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: near-01
  labels:
    app: near
spec:
  replicas: 2
  selector:
    matchLabels:
      app: near-v1
  template:
    metadata:
      labels:
        app: near-v1
    spec:
      containers:
        - name: near
          image: textile/near
          imagePullPolicy: Always
          ports:
            - name: api
              containerPort: 5000
            - name: metrics
              containerPort: 9090
          envFrom:
            - configMapRef:
                name: configmap-near
          resources:
            requests:
              cpu: 250m
              memory: 250Mi
          readinessProbe:
            tcpSocket:
              port: api
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: api
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3

