apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: packer-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: packer
---
apiVersion: v1
kind: Service
metadata:
  name: packer
  labels:
     app: packer
spec:
  selector:
    app: packer-v1
  ports:
    - port: 9090
      name: metrics
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: packer
  labels:
    app: packer
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      app: packer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: packer-01
  labels:
    app: packer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: packer-v1
  template:
    metadata:
      labels:
        app: packer-v1
    spec:
      serviceAccountName: postgres-cloud-sql
      containers:
        - name: packer
          image: textile/packer
          imagePullPolicy: Always
          ports:
            - name: metrics
              containerPort: 9090
          command: ["./with-postgres.sh", "./packerd"]
          env:
            - name: DAEMON
              value: "packer"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: postgres-password
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: packer-db-password
            - name: PACKER_GPUBSUB_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: gpubsub-project-id
            - name: PACKER_GPUBSUB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: gpubsub-api-key
          envFrom:
            - configMapRef:
                name: configmap-packer
          resources:
            requests:
              cpu: 500m
              memory: 512Mi

