apiVersion: v1
kind: Service
metadata:
  name: piecer
  labels:
     app: piecer
spec:
  selector:
    app: piecer-v1
  ports:
    - port: 9090
      name: metrics
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: piecer
  labels:
    app: piecer
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      app: piecer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: piecer-01
  labels:
    app: piecer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: piecer-v1
  template:
    metadata:
      labels:
        app: piecer-v1
    spec:
      serviceAccountName: postgres-cloud-sql
      containers:
        - name: piecer
          image: textile/piecer
          imagePullPolicy: Always
          ports:
            - name: metrics
              containerPort: 9090
          command: ["./with-postgres.sh", "./piecerd"]
          env:
            - name: DAEMON
              value: "piecer"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: postgres-password
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: piecer-db-password
            - name: PIECER_GPUBSUB_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: gpubsub-project-id
            - name: PIECER_GPUBSUB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: gpubsub-api-key
          envFrom:
            - configMapRef:
                name: configmap-piecer
          resources:
            requests:
              cpu: 250m
              memory: 512Mi

