apiVersion: v1
kind: Service
metadata:
  name: piecer
  labels:
     app: piecer
spec:
  selector:
    app: piecer-v1
  ports:
    - port: 5000
      name: api
    - port: 9090
      name: metrics
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: piecer
  labels:
    app: piecer
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      app: piecer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: piecer-01
  labels:
    app: piecer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piecer-v1
  template:
    metadata:
      labels:
        app: piecer-v1
    spec:
      containers:
        - name: piecer
          image: textile/piecer
          imagePullPolicy: Always
          ports:
            - name: api
              containerPort: 5000
            - name: metrics
              containerPort: 9090
          envFrom:
            - configMapRef:
                name: configmap-piecer
          resources:
            requests:
              memory: 300Mi
              cpu: "1"
            limits:
              cpu: "2"
              memory: 1Gi 
          readinessProbe:
            tcpSocket:
              port: api
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: api
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3

