apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: storage-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: storage
---
apiVersion: v1
kind: Service
metadata:
  name: storage
  labels:
    app: storage
  annotations:
    cloud.google.com/backend-config: '{"default": "broker-backendconfig"}'
spec:
  selector:
    app: storage-v1
  ports:
    - port: 8888
      name: api
    - port: 9090
      name: metrics
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: storage
  labels:
    app: storage
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      app: storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-01
  labels:
    app: storage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: storage-v1
  template:
    metadata:
      labels:
        app: storage-v1
    spec:
      containers:
        - name: storage
          image: textile/storage
          imagePullPolicy: Always
          ports:
            - name: api
              containerPort: 8888
            - name: metrics
              containerPort: 9090
          envFrom:
            - configMapRef:
                name: configmap-storage
          resources:
            requests:
              cpu: 100m
              memory: 250Mi
          readinessProbe:
            httpGet:
              port: api
              path: "/health"
          livenessProbe:
            tcpSocket:
              port: api
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3

