apiVersion: batch/v1
kind: Job
metadata:
  name: uploadbot
  namespace: broker-<ENV>
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: uploadbot
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: config-uploadbot
          configMap:
            name: uploadbot
            defaultMode: 0755
      containers:
        - name: uploadbot
          image: "node:16-buster"
          env:
            - name: COUNT
              value: "1000000000"
            - name: MIN_SIZE
              value: "1000"
            - name: MAX_SIZE
              value: "100000"
            - name: ENDPOINT
              value: "http://storage:8888"
            - name: SLEEP
              value: "2"
            - name: SEED_PHRASE
              value: "height unusual narrow dream follow grow rebel panda because then equip basic"
          volumeMounts:
            - name: config-uploadbot
              mountPath: bench.sh
              subPath: bench.sh
          command:
            - /bin/bash
            - -c
            - |
              set -x
              npm install -g near-cli
              ./bench.sh $ENDPOINT $MIN_SIZE $MAX_SIZE $COUNT $SLEEP
