// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/textileio/broker-core/gen/broker/auth/v1"

	mock "github.com/stretchr/testify/mock"
)

// APIServiceServer is an autogenerated mock type for the APIServiceServer type
type APIServiceServer struct {
	mock.Mock
}

// Auth provides a mock function with given fields: _a0, _a1
func (_m *APIServiceServer) Auth(_a0 context.Context, _a1 *auth.AuthRequest) (*auth.AuthResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *auth.AuthResponse
	if rf, ok := ret.Get(0).(func(context.Context, *auth.AuthRequest) *auth.AuthResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.AuthResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *auth.AuthRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedAPIServiceServer provides a mock function with given fields:
func (_m *APIServiceServer) mustEmbedUnimplementedAPIServiceServer() {
	_m.Called()
}
