// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type UnpreparedBatch struct {
	StorageDealID string    `json:"storageDealID"`
	Status        int16     `json:"status"`
	DataCid       string    `json:"dataCid"`
	ReadyAt       time.Time `json:"readyAt"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

type UnpreparedBatchesStatus struct {
	ID   int16  `json:"id"`
	Name string `json:"name"`
}
