// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"

	"github.com/textileio/broker-core/broker"
)

type UnpreparedBatch struct {
	StorageDealID broker.StorageDealID `json:"storageDealID"`
	Status        int16                `json:"status"`
	DataCid       string               `json:"dataCid"`
	ReadyAt       time.Time            `json:"readyAt"`
	CreatedAt     time.Time            `json:"createdAt"`
	UpdatedAt     time.Time            `json:"updatedAt"`
}

type UnpreparedBatchesStatus struct {
	ID   int16  `json:"id"`
	Name string `json:"name"`
}
