// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	peer "github.com/libp2p/go-libp2p-core/peer"
	mock "github.com/stretchr/testify/mock"
)

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

// Execute provides a mock function with given fields: from, topic, msg
func (_m *Handler) Execute(from peer.ID, topic string, msg []byte) {
	_m.Called(from, topic, msg)
}
