// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createBatchStmt, err = db.PrepareContext(ctx, createBatch); err != nil {
		return nil, fmt.Errorf("error preparing query CreateBatch: %w", err)
	}
	if q.createFinalDealStmt, err = db.PrepareContext(ctx, createFinalDeal); err != nil {
		return nil, fmt.Errorf("error preparing query CreateFinalDeal: %w", err)
	}
	if q.createStorageRequestStmt, err = db.PrepareContext(ctx, createStorageRequest); err != nil {
		return nil, fmt.Errorf("error preparing query CreateStorageRequest: %w", err)
	}
	if q.listAllStmt, err = db.PrepareContext(ctx, listAll); err != nil {
		return nil, fmt.Errorf("error preparing query ListAll: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createBatchStmt != nil {
		if cerr := q.createBatchStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createBatchStmt: %w", cerr)
		}
	}
	if q.createFinalDealStmt != nil {
		if cerr := q.createFinalDealStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createFinalDealStmt: %w", cerr)
		}
	}
	if q.createStorageRequestStmt != nil {
		if cerr := q.createStorageRequestStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createStorageRequestStmt: %w", cerr)
		}
	}
	if q.listAllStmt != nil {
		if cerr := q.listAllStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                       DBTX
	tx                       *sql.Tx
	createBatchStmt          *sql.Stmt
	createFinalDealStmt      *sql.Stmt
	createStorageRequestStmt *sql.Stmt
	listAllStmt              *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                       tx,
		tx:                       tx,
		createBatchStmt:          q.createBatchStmt,
		createFinalDealStmt:      q.createFinalDealStmt,
		createStorageRequestStmt: q.createStorageRequestStmt,
		listAllStmt:              q.listAllStmt,
	}
}
