// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Batch struct {
	ID                string   `json:"id"`
	StorageRequestIds []string `json:"storageRequestIds"`
}

type FinalDeal struct {
	BatchID           string         `json:"batchID"`
	StorageProviderID string         `json:"storageProviderID"`
	DealID            int64          `json:"dealID"`
	DealExpiration    int64          `json:"dealExpiration"`
	ErrorCause        sql.NullString `json:"errorCause"`
	Reported          sql.NullBool   `json:"reported"`
	Txn               sql.NullString `json:"txn"`
	CreatedAt         time.Time      `json:"createdAt"`
}

type StorageRequest struct {
	ID      string `json:"id"`
	DataCid string `json:"dataCid"`
	Origin  string `json:"origin"`
}
