// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	broker "github.com/textileio/broker-core/gen/broker/v1"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// APIServiceClient is an autogenerated mock type for the APIServiceClient type
type APIServiceClient struct {
	mock.Mock
}

// CreateBrokerRequest provides a mock function with given fields: ctx, in, opts
func (_m *APIServiceClient) CreateBrokerRequest(ctx context.Context, in *broker.CreateBrokerRequestRequest, opts ...grpc.CallOption) (*broker.CreateBrokerRequestResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *broker.CreateBrokerRequestResponse
	if rf, ok := ret.Get(0).(func(context.Context, *broker.CreateBrokerRequestRequest, ...grpc.CallOption) *broker.CreateBrokerRequestResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*broker.CreateBrokerRequestResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *broker.CreateBrokerRequestRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateStorageDeal provides a mock function with given fields: ctx, in, opts
func (_m *APIServiceClient) CreateStorageDeal(ctx context.Context, in *broker.CreateStorageDealRequest, opts ...grpc.CallOption) (*broker.CreateStorageDealResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *broker.CreateStorageDealResponse
	if rf, ok := ret.Get(0).(func(context.Context, *broker.CreateStorageDealRequest, ...grpc.CallOption) *broker.CreateStorageDealResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*broker.CreateStorageDealResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *broker.CreateStorageDealRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBrokerRequest provides a mock function with given fields: ctx, in, opts
func (_m *APIServiceClient) GetBrokerRequest(ctx context.Context, in *broker.GetBrokerRequestRequest, opts ...grpc.CallOption) (*broker.GetBrokerRequestResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *broker.GetBrokerRequestResponse
	if rf, ok := ret.Get(0).(func(context.Context, *broker.GetBrokerRequestRequest, ...grpc.CallOption) *broker.GetBrokerRequestResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*broker.GetBrokerRequestResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *broker.GetBrokerRequestRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageDealAuctioned provides a mock function with given fields: ctx, in, opts
func (_m *APIServiceClient) StorageDealAuctioned(ctx context.Context, in *broker.StorageDealAuctionedRequest, opts ...grpc.CallOption) (*broker.StorageDealAuctionedResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *broker.StorageDealAuctionedResponse
	if rf, ok := ret.Get(0).(func(context.Context, *broker.StorageDealAuctionedRequest, ...grpc.CallOption) *broker.StorageDealAuctionedResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*broker.StorageDealAuctionedResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *broker.StorageDealAuctionedRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
