// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ChainAPI is an autogenerated mock type for the ChainAPI type
type ChainAPI struct {
	mock.Mock
}

// HasDeposit provides a mock function with given fields: ctx, depositee, chainID
func (_m *ChainAPI) HasDeposit(ctx context.Context, depositee string, chainID string) (bool, error) {
	ret := _m.Called(ctx, depositee, chainID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, depositee, chainID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, depositee, chainID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
