// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	chainapi "github.com/textileio/broker-core/chainapi"
)

// UpdatePayloadOption is an autogenerated mock type for the UpdatePayloadOption type
type UpdatePayloadOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *UpdatePayloadOption) Execute(_a0 *chainapi.UpdatePayloadOptions) {
	_m.Called(_a0)
}
