// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	cid "github.com/ipfs/go-cid"
	"github.com/textileio/broker-core/broker"

	mock "github.com/stretchr/testify/mock"
)

// Piecer is an autogenerated mock type for the Piecer type
type Piecer struct {
	mock.Mock
}

// ReadyToPrepare provides a mock function with given fields: ctx, id, c
func (_m *Piecer) ReadyToPrepare(ctx context.Context, id broker.StorageDealID, c cid.Cid) error {
	ret := _m.Called(ctx, id, c)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, broker.StorageDealID, cid.Cid) error); ok {
		r0 = rf(ctx, id, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
