// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	types "github.com/textileio/broker-core/cmd/neard/nearclient/internal/types"
)

// ViewStateOption is an autogenerated mock type for the ViewStateOption type
type ViewStateOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *ViewStateOption) Execute(_a0 *types.QueryRequest) {
	_m.Called(_a0)
}
