// Code generated by sqlc. DO NOT EDIT.
// source: market_deal_status.sql

package db

import (
	"context"
	"database/sql"
)

const getMarketDealStatusForID = `-- name: GetMarketDealStatusForID :one
SELECT id, description, type FROM market_deal_status WHERE id = $1
`

func (q *Queries) GetMarketDealStatusForID(ctx context.Context, id int64) (MarketDealStatus, error) {
	row := q.queryRow(ctx, q.getMarketDealStatusForIDStmt, getMarketDealStatusForID, id)
	var i MarketDealStatus
	err := row.Scan(&i.ID, &i.Description, &i.Type)
	return i, err
}

const getMarketDealStatusForType = `-- name: GetMarketDealStatusForType :one
SELECT id, description, type FROM market_deal_status WHERE type = $1
`

func (q *Queries) GetMarketDealStatusForType(ctx context.Context, t sql.NullString) (MarketDealStatus, error) {
	row := q.queryRow(ctx, q.getMarketDealStatusForTypeStmt, getMarketDealStatusForType, t)
	var i MarketDealStatus
	err := row.Scan(&i.ID, &i.Description, &i.Type)
	return i, err
}
