// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeAPIServiceServer is an autogenerated mock type for the UnsafeAPIServiceServer type
type UnsafeAPIServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedAPIServiceServer provides a mock function with given fields:
func (_m *UnsafeAPIServiceServer) mustEmbedUnimplementedAPIServiceServer() {
	_m.Called()
}
