apiVersion: apps/v1
kind: Deployment
metadata:
  name: gql-01
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: gql
          env:
            - name: DEV
              value: "true"
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.17
          command:
            - "/cloud_sql_proxy"
            - "-instances=textile-310716:us-west1:broker-edge=tcp:5432"
          resources:
            requests:
              memory: "100Mi"
              cpu:    "0.5"
