// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type AuthToken struct {
	Token     string    `json:"token"`
	Identity  string    `json:"identity"`
	Origin    string    `json:"origin"`
	CreatedAt time.Time `json:"createdAt"`
}
