apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealer-01
spec:
  template:
    spec:
      containers:
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.17
          command:
            - "/cloud_sql_proxy"
            - "-instances=textile-310716:us-west1:broker-staging=tcp:5432"
          resources:
            requests:
              memory: "500Mi"
              cpu:    "0.5"
        - name: dealer
          env:
            - name: DEALER_LOTUS_EXPORTED_WALLET_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: dealer-lotus-exported-wallet-address
