apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-01
spec:
  template:
    spec:
      containers:
        - name: storage
          env:
            - name: STORAGE_PINATA_JWT
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: storage-pinata-jwt
