// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"fmt"
	"time"
)

type BatchStatus string

const (
	BatchStatusOpen  BatchStatus = "open"
	BatchStatusReady BatchStatus = "ready"
	BatchStatusDone  BatchStatus = "done"
)

func (e *BatchStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BatchStatus(s)
	case string:
		*e = BatchStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BatchStatus: %T", src)
	}
	return nil
}

type Batch struct {
	BatchID   string      `json:"batchID"`
	Status    BatchStatus `json:"status"`
	TotalSize int64       `json:"totalSize"`
	CreatedAt time.Time   `json:"createdAt"`
	UpdatedAt time.Time   `json:"updatedAt"`
}

type StorageRequest struct {
	StorageRequestID string         `json:"storageRequestID"`
	DataCid          string         `json:"dataCid"`
	BatchID          sql.NullString `json:"batchID"`
	CreatedAt        time.Time      `json:"createdAt"`
	UpdatedAt        time.Time      `json:"updatedAt"`
}
