// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	cid "github.com/ipfs/go-cid"
	broker "github.com/textileio/broker-core/broker"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Auctioneer is an autogenerated mock type for the Auctioneer type
type Auctioneer struct {
	mock.Mock
}

// GetAuction provides a mock function with given fields: ctx, id
func (_m *Auctioneer) GetAuction(ctx context.Context, id broker.AuctionID) (broker.Auction, error) {
	ret := _m.Called(ctx, id)

	var r0 broker.Auction
	if rf, ok := ret.Get(0).(func(context.Context, broker.AuctionID) broker.Auction); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(broker.Auction)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, broker.AuctionID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProposalAccepted provides a mock function with given fields: ctx, auID, bidID, proposalCid
func (_m *Auctioneer) ProposalAccepted(ctx context.Context, auID broker.AuctionID, bidID broker.BidID, proposalCid cid.Cid) error {
	ret := _m.Called(ctx, auID, bidID, proposalCid)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, broker.AuctionID, broker.BidID, cid.Cid) error); ok {
		r0 = rf(ctx, auID, bidID, proposalCid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReadyToAuction provides a mock function with given fields: ctx, id, dataCid, dealSize, dealDuration, dealReplication, dealVerified
func (_m *Auctioneer) ReadyToAuction(ctx context.Context, id broker.StorageDealID, dataCid cid.Cid, dealSize int, dealDuration int, dealReplication int, dealVerified bool) (broker.AuctionID, error) {
	ret := _m.Called(ctx, id, dataCid, dealSize, dealDuration, dealReplication, dealVerified)

	var r0 broker.AuctionID
	if rf, ok := ret.Get(0).(func(context.Context, broker.StorageDealID, cid.Cid, int, int, int, bool) broker.AuctionID); ok {
		r0 = rf(ctx, id, dataCid, dealSize, dealDuration, dealReplication, dealVerified)
	} else {
		r0 = ret.Get(0).(broker.AuctionID)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, broker.StorageDealID, cid.Cid, int, int, int, bool) error); ok {
		r1 = rf(ctx, id, dataCid, dealSize, dealDuration, dealReplication, dealVerified)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
