// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	cid "github.com/ipfs/go-cid"
	broker "github.com/textileio/bidbot/lib/broker"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Auctioneer is an autogenerated mock type for the Auctioneer type
type Auctioneer struct {
	mock.Mock
}

// GetAuction provides a mock function with given fields: ctx, id
func (_m *Auctioneer) GetAuction(ctx context.Context, id broker.AuctionID) (broker.Auction, error) {
	ret := _m.Called(ctx, id)

	var r0 broker.Auction
	if rf, ok := ret.Get(0).(func(context.Context, broker.AuctionID) broker.Auction); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(broker.Auction)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, broker.AuctionID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProposalAccepted provides a mock function with given fields: ctx, auID, bidID, proposalCid
func (_m *Auctioneer) ProposalAccepted(ctx context.Context, auID broker.AuctionID, bidID broker.BidID, proposalCid cid.Cid) error {
	ret := _m.Called(ctx, auID, bidID, proposalCid)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, broker.AuctionID, broker.BidID, cid.Cid) error); ok {
		r0 = rf(ctx, auID, bidID, proposalCid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReadyToAuction provides a mock function with given fields: ctx, id, payloadCid, dealSize, dealDuration, dealReplication, dealVerified, excludedMiners, filEpochDeadline, sources
func (_m *Auctioneer) ReadyToAuction(ctx context.Context, id broker.StorageDealID, payloadCid cid.Cid, dealSize int, dealDuration int, dealReplication int, dealVerified bool, excludedMiners []string, filEpochDeadline uint64, sources broker.Sources) (broker.AuctionID, error) {
	ret := _m.Called(ctx, id, payloadCid, dealSize, dealDuration, dealReplication, dealVerified, excludedMiners, filEpochDeadline, sources)

	var r0 broker.AuctionID
	if rf, ok := ret.Get(0).(func(context.Context, broker.StorageDealID, cid.Cid, int, int, int, bool, []string, uint64, broker.Sources) broker.AuctionID); ok {
		r0 = rf(ctx, id, payloadCid, dealSize, dealDuration, dealReplication, dealVerified, excludedMiners, filEpochDeadline, sources)
	} else {
		r0 = ret.Get(0).(broker.AuctionID)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, broker.StorageDealID, cid.Cid, int, int, int, bool, []string, uint64, broker.Sources) error); ok {
		r1 = rf(ctx, id, payloadCid, dealSize, dealDuration, dealReplication, dealVerified, excludedMiners, filEpochDeadline, sources)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
